// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32HKT2AZoPFXEREemGfOUxUu2AiJKJis',
    appId: '1:610695137883:web:6ad2ea542f9d13490c8d7e',
    messagingSenderId: '610695137883',
    projectId: 'notes-5d778',
    authDomain: 'notes-5d778.firebaseapp.com',
    storageBucket: 'notes-5d778.appspot.com',
    measurementId: 'G-B93B8TTF1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpdlakNkRN0nT0YgVV5NeayVPwfv521Y',
    appId: '1:610695137883:android:4c84ed6a195b946d0c8d7e',
    messagingSenderId: '610695137883',
    projectId: 'notes-5d778',
    storageBucket: 'notes-5d778.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP3NbRyAb64tDuvMCSvIUyspwqI13NH-Q',
    appId: '1:610695137883:ios:c47eb8731a7c52f20c8d7e',
    messagingSenderId: '610695137883',
    projectId: 'notes-5d778',
    storageBucket: 'notes-5d778.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3NbRyAb64tDuvMCSvIUyspwqI13NH-Q',
    appId: '1:610695137883:ios:c47eb8731a7c52f20c8d7e',
    messagingSenderId: '610695137883',
    projectId: 'notes-5d778',
    storageBucket: 'notes-5d778.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB32HKT2AZoPFXEREemGfOUxUu2AiJKJis',
    appId: '1:610695137883:web:6f0846584ccbf5680c8d7e',
    messagingSenderId: '610695137883',
    projectId: 'notes-5d778',
    authDomain: 'notes-5d778.firebaseapp.com',
    storageBucket: 'notes-5d778.appspot.com',
    measurementId: 'G-RB4EF4MQ3K',
  );

}